name: Build Docker Image for Synology

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate build date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64
        outputs: type=docker,dest=./alist-synology.tar

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true  # 自动生成简洁说明
        tag_name: build-${{ github.run_id }}  # 唯一构建标签
        name: "Alist Synology Build #${{ github.run_number }}"
        files: |
          alist-synology.tar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
