name: Build Docker Image for Synology

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Export Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64
        outputs: type=docker,dest=./alist-synology.tar
        tags: cerha3688/alist-synology:latest

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: alist-docker-image
        path: ./alist-synology.tar
